PUT http://localhost:3001/api/persons/64e9234b7f1cec53f3262a07
Content-Type: application/json

{
  "name": "replaced",
  "number": "1423"
}

###
PUT http://localhost:3001/api/persons/64e922da3d5e9a7860cacd